### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by aschulz01**
Hi Marc, 

today I created a bower registration entry for you.
(linked to this repository, by calling bower register sp-services https://github.com/sympmarc/SPServices.git)

Could you change the version schema to Semantic Version ("http://semver.org/"). 

It's needed to change the release tags as well (e.g. "14.2.0"). I'm afraid it's needed to re-release, due to the non semantic Version in tagged the bower.json files.

I forked your repository, and registered this fork on bower to show a working solution of the release schema https://github.com/aschulz01/SPServices/ .
(the bower package for that is sp-services-aschulz, that I will delete if your package-registration is working)

best regards 
Andreas

### CODE REVIEW

**Comment by johnnliu** [comment]
I think changing version number system to semantic version would have some impact to existing systems.

Especially considering that 2014.01/02 was just a new thing last year.

Personally I think it is worthwhile to move to something compatible with semantic versioning like

2014.2.0

I can't agree with shortening the 20- prefix because that would imply the new version is a smaller number than the previous version.  To me, version 2014 and version 14 aren't the same things.  I'm also expecting the next feature update to be 2015.01

Also, the 201x yearly prefixes would imply that there's a major backward breaking change every year when that's not really the case.

Anyway, I just wanted to add a few cents on what I think.  I think this PR needs discussion.

Sent from my Windows Phone
________________________________

**Comment by purtuga** [comment]
I too think that going with semantic convention is a good move.  And one
that would support package mangers like bower.

Marc has been entertaining the thought of adding older versions of
SPServices to github.  This would be the opportunity to re-think the entire
naming convention.  I like John's suggestion, about keeping the first digit
as the year. That would more closely resemble what Marc was attempting to
do with this convention and as John pointed out, it maintains a hierarchal
structure (2015.0.0 is newer than 2014.0.0).

My personal thoughts: forget the concept of trying to tie your versions of
SPServices to a year and instead go with full support of semantic
versioning.  Having the version number imply that there are possible
backwards incompatible changes is a very beneficial feature.  And one that
all package managers automatically support with special tokens (^2.3.4, or
~2.3.4).





-- 
Paul T.

-- Sent from Mobile

**Comment by sympmarc** [comment]
I started to add my thoughts here and it turned into a blog post: Semantic Versioning for SPServices? http://ow.ly/GT9ae

M.

**Comment by sympmarc** [comment]
@aschulz01: We're now working on SPServices 2.0, which should be semantically correct. I'm going to close this pull request, but feel free to add another against the updated code base.

**Pull request closed without merging**
